apiVersion: v1
kind: Namespace
metadata:
  name: es-operator-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: es-operator
  namespace: es-operator-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-operator
  namespace: es-operator-demo
  labels:
    application: es-operator
    version: latest
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: es-operator
  template:
    metadata:
      labels:
        application: es-operator
        version: latest
    spec:
      serviceAccountName: es-operator
      containers:
      - name: es-operator
        image: es-operator-local:v0.1.3-21-g4ad2302-dirty
        args:
          - --interval=30s
          - --namespace=es-operator-demo
          - --debug
        resources:
          limits:
            cpu: 20m
            memory: 100Mi
          requests:
            cpu: 20m
            memory: 100Mi
